- block:
  - name: undeploy prometheus-operator on cluster
    shell: "{{ kubectl_path }}/kubectl --kubeconfig {{ kubeconfig_file }} -n {{ deploy_namespace }} delete -f /root/monitoring/prometheus_operator/manifests/"

  - name: remove directory containing manifests for prometheus-operator
    file:
      path: /root/monitoring/prometheus_operator/manifests
      state: absent

  when: inventory_hostname == groups['master'][0]