- block:
  - name: copy manifest file for prometheus-operator
    copy:
      src: manifests
      dest: /root/monitoring/prometheus_operator/
      owner: root
      group: root
      
  - name: copy clusterrolebinding file for prometheus-operator with dynamic namespace
    template:
      src: 0prometheus-operator-clusterRoleBinding.yaml.tpl
      dest: /root/monitoring/prometheus_operator/manifests/0prometheus-operator-clusterRoleBinding.yaml
      owner: root
      group: root

  - name: create priority class for monitoring workload
    shell: "{{ kubectl_path }}/kubectl --kubeconfig {{ kubeconfig_file }} create priorityclass monitoring-critical --value=100000000 --description=\"monitoring workload priority\""
    ignore_errors: yes

  - name: create namespace for monitoring staff on cluster
    shell: "{{ kubectl_path }}/kubectl --kubeconfig {{ kubeconfig_file }} create ns {{ deploy_namespace }}"
    ignore_errors: yes
  
  - name: deploy prometheus-operator on cluster
    shell: "{{ kubectl_path }}/kubectl --kubeconfig {{ kubeconfig_file }} -n {{ deploy_namespace }} apply -f /root/monitoring/prometheus_operator/manifests/"
    register: result
    until: result is succeeded
    retries: 10
    delay: 10

  when: inventory_hostname == groups['master'][0]