- block:

  - name: remove secret if exists
    shell: "{{ kubectl_path }}/kubectl --kubeconfig {{ kubeconfig_file }} -n {{ deploy_namespace }} delete secret {{ secret_item.name }} --ignore-not-found"

  when: inventory_hostname == groups['master'][0]