- block:

  - name: create secret
    shell: "{{ kubectl_path }}/kubectl --kubeconfig {{ kubeconfig_file }} -n {{ deploy_namespace }} create secret {{ secret_item.type | default('generic') }} {{ secret_item.creation }}"

  when: inventory_hostname == groups['master'][0]