- block:

  - name: remove secret if exists
    shell: "{{ kubectl_path }}/kubectl --kubeconfig {{ kubeconfig_file }} -n {{ deploy_namespace }} delete secret {{ secret_item.name }} --ignore-not-found"
  
  - name: create secret
    shell: "{{ kubectl_path }}/kubectl --kubeconfig {{ kubeconfig_file }} -n {{ deploy_namespace }} create secret {{ secret_item.type | default('generic') }} {{ secret_item.name }} {{ secret_item.creation }}"

  when: inventory_hostname == groups['master'][0]